// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Telnyx.OpenApiClient.Email_threads.Item;
using Soenneker.Telnyx.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Email_threads
{
    /// <summary>
    /// Builds and executes requests for operations under \email_threads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Email_threadsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Telnyx.OpenApiClient.email_threads.item collection</summary>
        /// <param name="position">Email thread UUID.</param>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Email_threads.Item.WithThreadItemRequestBuilder"/></returns>
        public global::Soenneker.Telnyx.OpenApiClient.Email_threads.Item.WithThreadItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("threadId", position);
                return new global::Soenneker.Telnyx.OpenApiClient.Email_threads.Item.WithThreadItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Email_threadsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/email_threads{?filter%5Binbox_id%5D*,filter%5Blabel%5D*,page%5Bafter%5D*,page%5Bsize%5D*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Email_threadsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/email_threads{?filter%5Binbox_id%5D*,filter%5Blabel%5D*,page%5Bafter%5D*,page%5Bsize%5D*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists thread summaries for the whole account, newest first, using stablecursor pagination. An agent operating many inboxes gets everyconversation in one call instead of one call per inbox. Each threadcarries its own `inbox_id` so a reply can be routed back to the rightinbox. Use `filter[inbox_id]` (repeatable) to narrow the result tospecific inboxes. Because a thread ID can be delivered to multipleinboxes, each result is identified by its `(inbox_id, id)` pair.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InboundThreadListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Telnyx.OpenApiClient.Models.InboundThreadListResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder.Email_threadsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Telnyx.OpenApiClient.Models.InboundThreadListResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder.Email_threadsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Telnyx.OpenApiClient.Models.EmailErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Telnyx.OpenApiClient.Models.InboundThreadListResponse>(requestInfo, global::Soenneker.Telnyx.OpenApiClient.Models.InboundThreadListResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists thread summaries for the whole account, newest first, using stablecursor pagination. An agent operating many inboxes gets everyconversation in one call instead of one call per inbox. Each threadcarries its own `inbox_id` so a reply can be routed back to the rightinbox. Use `filter[inbox_id]` (repeatable) to narrow the result tospecific inboxes. Because a thread ID can be delivered to multipleinboxes, each result is identified by its `(inbox_id, id)` pair.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder.Email_threadsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder.Email_threadsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Telnyx.OpenApiClient.Email_threads.Email_threadsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists thread summaries for the whole account, newest first, using stablecursor pagination. An agent operating many inboxes gets everyconversation in one call instead of one call per inbox. Each threadcarries its own `inbox_id` so a reply can be routed back to the rightinbox. Use `filter[inbox_id]` (repeatable) to narrow the result tospecific inboxes. Because a thread ID can be delivered to multipleinboxes, each result is identified by its `(inbox_id, id)` pair.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Email_threadsRequestBuilderGetQueryParameters 
        {
            /// <summary>Restrict results to one or more inboxes. Repeat the parameter(`filter[inbox_id][]=...&amp;filter[inbox_id][]=...`) or pass acomma-separated list. Omit to list every inbox in the account.Inboxes outside the account are silently excluded. If the filteris present, it must contain at least one non-empty UUID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Binbox_id%5D")]
            public Guid?[]? FilterinboxId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Binbox_id%5D")]
            public Guid?[] FilterinboxId { get; set; }
#endif
            /// <summary>Returns only threads carrying this label. Matching is exact and case-sensitive. Thread labels are independent of the labels on the thread&apos;s messages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%5Blabel%5D")]
            public string? Filterlabel { get; set; }
#nullable restore
#else
            [QueryParameter("filter%5Blabel%5D")]
            public string Filterlabel { get; set; }
#endif
            /// <summary>Opaque cursor returned by the previous page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page%5Bafter%5D")]
            public string? Pageafter { get; set; }
#nullable restore
#else
            [QueryParameter("page%5Bafter%5D")]
            public string Pageafter { get; set; }
#endif
            /// <summary>Number of results to return. Defaults to 25; maximum is 100.</summary>
            [QueryParameter("page%5Bsize%5D")]
            public int? Pagesize { get; set; }
        }
    }
}
#pragma warning restore CS0618
