// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BrandUpdateRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequestAddressesProperty? Addresses { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequestAddressesProperty Addresses { get; set; }
#endif
        /// <summary>Named business contacts. Use the `brand` key for the required BRAND contact.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandContacts? Contacts { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandContacts Contacts { get; set; }
#endif
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Named business identifiers. Use the `ein` key for the required EIN and `stock_symbol` for a public-profit brand&apos;s stock symbol.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandIdentifiers? Identifiers { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandIdentifiers Identifiers { get; set; }
#endif
        /// <summary>The legal_entity_type property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandLegalEntityType? LegalEntityType { get; set; }
        /// <summary>The legal_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalName { get; set; }
#nullable restore
#else
        public string LegalName { get; set; }
#endif
        /// <summary>The organization_type property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.BrandOrganizationType? OrganizationType { get; set; }
        /// <summary>The profile_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileId { get; set; }
#nullable restore
#else
        public string ProfileId { get; set; }
#endif
        /// <summary>The website_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebsiteUrl { get; set; }
#nullable restore
#else
        public string WebsiteUrl { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addresses", n => { Addresses = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequestAddressesProperty>(global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequestAddressesProperty.CreateFromDiscriminatorValue); } },
                { "contacts", n => { Contacts = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandContacts>(global::Soenneker.Telnyx.OpenApiClient.Models.BrandContacts.CreateFromDiscriminatorValue); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "identifiers", n => { Identifiers = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandIdentifiers>(global::Soenneker.Telnyx.OpenApiClient.Models.BrandIdentifiers.CreateFromDiscriminatorValue); } },
                { "legal_entity_type", n => { LegalEntityType = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandLegalEntityType>(); } },
                { "legal_name", n => { LegalName = n.GetStringValue(); } },
                { "organization_type", n => { OrganizationType = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandOrganizationType>(); } },
                { "profile_id", n => { ProfileId = n.GetStringValue(); } },
                { "website_url", n => { WebsiteUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandUpdateRequestAddressesProperty>("addresses", Addresses);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandContacts>("contacts", Contacts);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandIdentifiers>("identifiers", Identifiers);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandLegalEntityType>("legal_entity_type", LegalEntityType);
            writer.WriteStringValue("legal_name", LegalName);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.BrandOrganizationType>("organization_type", OrganizationType);
            writer.WriteStringValue("profile_id", ProfileId);
            writer.WriteStringValue("website_url", WebsiteUrl);
        }
    }
}
#pragma warning restore CS0618
