// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>Brand relationship to the CSP.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BrandRelationship
    {
        [EnumMember(Value = "BASIC_ACCOUNT")]
        #pragma warning disable CS1591
        BasicAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "SMALL_ACCOUNT")]
        #pragma warning disable CS1591
        SmallAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "MEDIUM_ACCOUNT")]
        #pragma warning disable CS1591
        MediumAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "LARGE_ACCOUNT")]
        #pragma warning disable CS1591
        LargeAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "KEY_ACCOUNT")]
        #pragma warning disable CS1591
        KeyAccount,
        #pragma warning restore CS1591
    }
}
