// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The reason for leaving the queue</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CallLeftQueueBodyPayloadReason
    {
        [EnumMember(Value = "bridged")]
        #pragma warning disable CS1591
        Bridged,
        #pragma warning restore CS1591
        [EnumMember(Value = "bridging-in-process")]
        #pragma warning disable CS1591
        BridgingInProcess,
        #pragma warning restore CS1591
        [EnumMember(Value = "hangup")]
        #pragma warning disable CS1591
        Hangup,
        #pragma warning restore CS1591
        [EnumMember(Value = "leave")]
        #pragma warning disable CS1591
        Leave,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeout")]
        #pragma warning disable CS1591
        Timeout,
        #pragma warning restore CS1591
    }
}
