// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>Indication that there was a problem recording the call.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CallRecordingErrorBodyPayloadReason
    {
        [EnumMember(Value = "Failed to authorize with storage using custom credentials")]
        #pragma warning disable CS1591
        FailedToAuthorizeWithStorageUsingCustomCredentials,
        #pragma warning restore CS1591
        [EnumMember(Value = "Invalid credentials json")]
        #pragma warning disable CS1591
        InvalidCredentialsJson,
        #pragma warning restore CS1591
        [EnumMember(Value = "Unsupported backend")]
        #pragma warning disable CS1591
        UnsupportedBackend,
        #pragma warning restore CS1591
        [EnumMember(Value = "Internal server error")]
        #pragma warning disable CS1591
        InternalServerError,
        #pragma warning restore CS1591
    }
}
