// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The event that triggered the callback.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConferenceStartStatusCallbackEvent
    {
        [EnumMember(Value = "conference-start")]
        #pragma warning disable CS1591
        ConferenceStart,
        #pragma warning restore CS1591
    }
}
