// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The type of event being delivered.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConferenceEndedEventType
    {
        [EnumMember(Value = "conference.ended")]
        #pragma warning disable CS1591
        ConferenceEnded,
        #pragma warning restore CS1591
    }
}
