// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Counts of the authenticated user&apos;s connections, grouped by connection type. Forward-only connections are excluded.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConnectionsCountCounts : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Number of Call Control applications.</summary>
        public int? CallControlApplications { get; set; }
        /// <summary>Number of credential connections.</summary>
        public int? CredentialConnections { get; set; }
        /// <summary>Number of external connections.</summary>
        public int? ExternalConnections { get; set; }
        /// <summary>Number of Fax applications.</summary>
        public int? FaxConnections { get; set; }
        /// <summary>Number of FQDN connections.</summary>
        public int? FqdnConnections { get; set; }
        /// <summary>Number of IP connections.</summary>
        public int? IpConnections { get; set; }
        /// <summary>Number of Microsoft Teams SBC (direct routing) connections.</summary>
        public int? MicrosoftTeamsSbcConnections { get; set; }
        /// <summary>Number of mobile voice (IMS) connections.</summary>
        public int? MobileVoiceConnections { get; set; }
        /// <summary>Number of Microsoft Operator Connect connections.</summary>
        public int? OperatorConnectConnections { get; set; }
        /// <summary>Number of TeXML applications.</summary>
        public int? TexmlApplications { get; set; }
        /// <summary>Number of third-party provider connections.</summary>
        public int? ThirdPartyProviderConnections { get; set; }
        /// <summary>Number of UAC connections.</summary>
        public int? UacConnections { get; set; }
        /// <summary>Number of Zoom SBC connections.</summary>
        public int? ZoomSbcConnections { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.ConnectionsCountCounts"/> and sets the default values.
        /// </summary>
        public ConnectionsCountCounts()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.ConnectionsCountCounts"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.ConnectionsCountCounts CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.ConnectionsCountCounts();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "call_control_applications", n => { CallControlApplications = n.GetIntValue(); } },
                { "credential_connections", n => { CredentialConnections = n.GetIntValue(); } },
                { "external_connections", n => { ExternalConnections = n.GetIntValue(); } },
                { "fax_connections", n => { FaxConnections = n.GetIntValue(); } },
                { "fqdn_connections", n => { FqdnConnections = n.GetIntValue(); } },
                { "ip_connections", n => { IpConnections = n.GetIntValue(); } },
                { "microsoft_teams_sbc_connections", n => { MicrosoftTeamsSbcConnections = n.GetIntValue(); } },
                { "mobile_voice_connections", n => { MobileVoiceConnections = n.GetIntValue(); } },
                { "operator_connect_connections", n => { OperatorConnectConnections = n.GetIntValue(); } },
                { "texml_applications", n => { TexmlApplications = n.GetIntValue(); } },
                { "third_party_provider_connections", n => { ThirdPartyProviderConnections = n.GetIntValue(); } },
                { "uac_connections", n => { UacConnections = n.GetIntValue(); } },
                { "zoom_sbc_connections", n => { ZoomSbcConnections = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("call_control_applications", CallControlApplications);
            writer.WriteIntValue("credential_connections", CredentialConnections);
            writer.WriteIntValue("external_connections", ExternalConnections);
            writer.WriteIntValue("fax_connections", FaxConnections);
            writer.WriteIntValue("fqdn_connections", FqdnConnections);
            writer.WriteIntValue("ip_connections", IpConnections);
            writer.WriteIntValue("microsoft_teams_sbc_connections", MicrosoftTeamsSbcConnections);
            writer.WriteIntValue("mobile_voice_connections", MobileVoiceConnections);
            writer.WriteIntValue("operator_connect_connections", OperatorConnectConnections);
            writer.WriteIntValue("texml_applications", TexmlApplications);
            writer.WriteIntValue("third_party_provider_connections", ThirdPartyProviderConnections);
            writer.WriteIntValue("uac_connections", UacConnections);
            writer.WriteIntValue("zoom_sbc_connections", ZoomSbcConnections);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
