// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DirPhoneNumber : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Id of the batch this number was vetted as part of.</summary>
        public Guid? BatchId { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>The dir_id property</summary>
        public Guid? DirId { get; set; }
        /// <summary>The enterprise_id property</summary>
        public Guid? EnterpriseId { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; private set; }
        /// <summary>Id of the Letter of Authorization document attached to this number&apos;s batch.</summary>
        public Guid? LoaDocumentId { get; set; }
        /// <summary>E.164 with leading `+`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>The rejection_reason property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.RejectionReason? RejectionReason { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.RejectionReason RejectionReason { get; set; }
#endif
        /// <summary>Phone-number lifecycle status.- `submitted` / `in_review` - Telnyx is reviewing the batch this number belongs to.- `verified` - approved; the DIR&apos;s display identity will be shown on outbound calls from this number.- `unsuccessful` - Telnyx rejected this submission; the customer may re-add to retry.- `suspended` - temporarily disabled (e.g. by an active infringement claim on the DIR).- `expired` - verification expired; re-add to renew.- `permanently_rejected` - terminal; cannot be re-added on this or any other DIR you own.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberStatus? Status { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>The verified_at property</summary>
        public DateTimeOffset? VerifiedAt { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.DirPhoneNumber"/> and sets the default values.
        /// </summary>
        public DirPhoneNumber()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.DirPhoneNumber"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.DirPhoneNumber CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.DirPhoneNumber();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "batch_id", n => { BatchId = n.GetGuidValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "dir_id", n => { DirId = n.GetGuidValue(); } },
                { "enterprise_id", n => { EnterpriseId = n.GetGuidValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "loa_document_id", n => { LoaDocumentId = n.GetGuidValue(); } },
                { "phone_number", n => { PhoneNumber = n.GetStringValue(); } },
                { "rejection_reason", n => { RejectionReason = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.RejectionReason>(global::Soenneker.Telnyx.OpenApiClient.Models.RejectionReason.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberStatus>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "verified_at", n => { VerifiedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("batch_id", BatchId);
            writer.WriteGuidValue("dir_id", DirId);
            writer.WriteGuidValue("enterprise_id", EnterpriseId);
            writer.WriteGuidValue("loa_document_id", LoaDocumentId);
            writer.WriteStringValue("phone_number", PhoneNumber);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.RejectionReason>("rejection_reason", RejectionReason);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
