// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The antivirus scan status of the document.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DocServiceDocumentAllOf2AvScanStatus
    {
        [EnumMember(Value = "scanned")]
        #pragma warning disable CS1591
        Scanned,
        #pragma warning restore CS1591
        [EnumMember(Value = "infected")]
        #pragma warning disable CS1591
        Infected,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending_scan")]
        #pragma warning disable CS1591
        PendingScan,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_scanned")]
        #pragma warning disable CS1591
        NotScanned,
        #pragma warning restore CS1591
    }
}
