// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>Batch item errors use `message` (not `detail`) for the human-readable text.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmailBatchItemErrorCode
    {
        [EnumMember(Value = "bad_request")]
        #pragma warning disable CS1591
        BadRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_found")]
        #pragma warning disable CS1591
        NotFound,
        #pragma warning restore CS1591
        [EnumMember(Value = "forbidden")]
        #pragma warning disable CS1591
        Forbidden,
        #pragma warning restore CS1591
        [EnumMember(Value = "service_unavailable")]
        #pragma warning disable CS1591
        ServiceUnavailable,
        #pragma warning restore CS1591
        [EnumMember(Value = "validation_error")]
        #pragma warning disable CS1591
        ValidationError,
        #pragma warning restore CS1591
        [EnumMember(Value = "recipient_suppressed")]
        #pragma warning disable CS1591
        RecipientSuppressed,
        #pragma warning restore CS1591
        [EnumMember(Value = "reputation_suspended")]
        #pragma warning disable CS1591
        ReputationSuspended,
        #pragma warning restore CS1591
    }
}
