// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnterprisePublic : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billing_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.BillingAddress? BillingAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.BillingAddress BillingAddress { get; set; }
#endif
        /// <summary>The billing_contact property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.BillingContact? BillingContact { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.BillingContact BillingContact { get; set; }
#endif
        /// <summary>Corporate registration number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CorporateRegistrationNumber { get; set; }
#nullable restore
#else
        public string CorporateRegistrationNumber { get; set; }
#endif
        /// <summary>ISO 3166-1 alpha-2 country code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>When the enterprise was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Customer reference identifier</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerReference { get; set; }
#nullable restore
#else
        public string CustomerReference { get; set; }
#endif
        /// <summary>DBA name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DoingBusinessAs { get; set; }
#nullable restore
#else
        public string DoingBusinessAs { get; set; }
#endif
        /// <summary>D-U-N-S Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DunBradstreetNumber { get; set; }
#nullable restore
#else
        public string DunBradstreetNumber { get; set; }
#endif
        /// <summary>Federal Employer Identification Number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fein { get; set; }
#nullable restore
#else
        public string Fein { get; set; }
#endif
        /// <summary>Unique identifier of the enterprise</summary>
        public Guid? Id { get; set; }
        /// <summary>Industry classification</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Industry { get; set; }
#nullable restore
#else
        public string Industry { get; set; }
#endif
        /// <summary>Legal name of the enterprise</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalName { get; set; }
#nullable restore
#else
        public string LegalName { get; set; }
#endif
        /// <summary>Employee count range</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_number_of_employees? NumberOfEmployees { get; set; }
        /// <summary>&quot;Organization contact information. Note: the response returns this object with the phone field as &apos;phone&apos; (not &apos;phone_number&apos;).&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.OrganizationContact? OrganizationContact { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.OrganizationContact OrganizationContact { get; set; }
#endif
        /// <summary>Legal structure type</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_organization_legal_type? OrganizationLegalType { get; set; }
        /// <summary>The organization_physical_address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.PhysicalAddress? OrganizationPhysicalAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.PhysicalAddress OrganizationPhysicalAddress { get; set; }
#endif
        /// <summary>Type of organization</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_organization_type? OrganizationType { get; set; }
        /// <summary>SIC Code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PrimaryBusinessDomainSicCode { get; set; }
#nullable restore
#else
        public string PrimaryBusinessDomainSicCode { get; set; }
#endif
        /// <summary>Professional license number</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfessionalLicenseNumber { get; set; }
#nullable restore
#else
        public string ProfessionalLicenseNumber { get; set; }
#endif
        /// <summary>Role type in Branded Calling / Number Reputation services</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_role_type? RoleType { get; set; }
        /// <summary>When the enterprise was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Company website URL</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Website { get; set; }
#nullable restore
#else
        public string Website { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic"/> and sets the default values.
        /// </summary>
        public EnterprisePublic()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_address", n => { BillingAddress = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BillingAddress>(global::Soenneker.Telnyx.OpenApiClient.Models.BillingAddress.CreateFromDiscriminatorValue); } },
                { "billing_contact", n => { BillingContact = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BillingContact>(global::Soenneker.Telnyx.OpenApiClient.Models.BillingContact.CreateFromDiscriminatorValue); } },
                { "corporate_registration_number", n => { CorporateRegistrationNumber = n.GetStringValue(); } },
                { "country_code", n => { CountryCode = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "customer_reference", n => { CustomerReference = n.GetStringValue(); } },
                { "doing_business_as", n => { DoingBusinessAs = n.GetStringValue(); } },
                { "dun_bradstreet_number", n => { DunBradstreetNumber = n.GetStringValue(); } },
                { "fein", n => { Fein = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "industry", n => { Industry = n.GetStringValue(); } },
                { "legal_name", n => { LegalName = n.GetStringValue(); } },
                { "number_of_employees", n => { NumberOfEmployees = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_number_of_employees>(); } },
                { "organization_contact", n => { OrganizationContact = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.OrganizationContact>(global::Soenneker.Telnyx.OpenApiClient.Models.OrganizationContact.CreateFromDiscriminatorValue); } },
                { "organization_legal_type", n => { OrganizationLegalType = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_organization_legal_type>(); } },
                { "organization_physical_address", n => { OrganizationPhysicalAddress = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.PhysicalAddress>(global::Soenneker.Telnyx.OpenApiClient.Models.PhysicalAddress.CreateFromDiscriminatorValue); } },
                { "organization_type", n => { OrganizationType = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_organization_type>(); } },
                { "primary_business_domain_sic_code", n => { PrimaryBusinessDomainSicCode = n.GetStringValue(); } },
                { "professional_license_number", n => { ProfessionalLicenseNumber = n.GetStringValue(); } },
                { "role_type", n => { RoleType = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_role_type>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "website", n => { Website = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BillingAddress>("billing_address", BillingAddress);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.BillingContact>("billing_contact", BillingContact);
            writer.WriteStringValue("corporate_registration_number", CorporateRegistrationNumber);
            writer.WriteStringValue("country_code", CountryCode);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("customer_reference", CustomerReference);
            writer.WriteStringValue("doing_business_as", DoingBusinessAs);
            writer.WriteStringValue("dun_bradstreet_number", DunBradstreetNumber);
            writer.WriteStringValue("fein", Fein);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("industry", Industry);
            writer.WriteStringValue("legal_name", LegalName);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_number_of_employees>("number_of_employees", NumberOfEmployees);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.OrganizationContact>("organization_contact", OrganizationContact);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_organization_legal_type>("organization_legal_type", OrganizationLegalType);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.PhysicalAddress>("organization_physical_address", OrganizationPhysicalAddress);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_organization_type>("organization_type", OrganizationType);
            writer.WriteStringValue("primary_business_domain_sic_code", PrimaryBusinessDomainSicCode);
            writer.WriteStringValue("professional_license_number", ProfessionalLicenseNumber);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnterprisePublic_role_type>("role_type", RoleType);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("website", Website);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
