// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EnterpriseReputationPublic : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>How often Telnyx refreshes the stored reputation data for this enterprise&apos;s registered numbers.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.ReputationCheckFrequency? CheckFrequency { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>The enterprise_id property</summary>
        public Guid? EnterpriseId { get; set; }
        /// <summary>Id of the signed LOA document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LoaDocumentId { get; set; }
#nullable restore
#else
        public string LoaDocumentId { get; set; }
#endif
        /// <summary>Customer-facing Letter-of-Authorization verification state. `approved` is required (alongside reputation status) before phone numbers can be added.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.ReputationLoaStatusPublic? LoaStatus { get; set; }
        /// <summary>Populated when `status` is `rejected`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? RejectionReasons { get; set; }
#nullable restore
#else
        public List<string> RejectionReasons { get; set; }
#endif
        /// <summary>Lifecycle status of the enterprise&apos;s Phone Number Reputation activation.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.ReputationStatus? Status { get; set; }
        /// <summary>The updated_at property</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnterpriseReputationPublic"/> and sets the default values.
        /// </summary>
        public EnterpriseReputationPublic()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnterpriseReputationPublic"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.EnterpriseReputationPublic CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.EnterpriseReputationPublic();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "check_frequency", n => { CheckFrequency = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.ReputationCheckFrequency>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "enterprise_id", n => { EnterpriseId = n.GetGuidValue(); } },
                { "loa_document_id", n => { LoaDocumentId = n.GetStringValue(); } },
                { "loa_status", n => { LoaStatus = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.ReputationLoaStatusPublic>(); } },
                { "rejection_reasons", n => { RejectionReasons = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.ReputationStatus>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.ReputationCheckFrequency>("check_frequency", CheckFrequency);
            writer.WriteGuidValue("enterprise_id", EnterpriseId);
            writer.WriteStringValue("loa_document_id", LoaDocumentId);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.ReputationLoaStatusPublic>("loa_status", LoaStatus);
            writer.WriteCollectionOfPrimitiveValues<string>("rejection_reasons", RejectionReasons);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.ReputationStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
