// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>&quot;Country where you would like to purchase phone numbers. Allowable values: US, CA&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InexplicitNumberOrderRequestOrderingGroupsItemCountryIso
    {
        [EnumMember(Value = "US")]
        #pragma warning disable CS1591
        Us,
        #pragma warning restore CS1591
        [EnumMember(Value = "CA")]
        #pragma warning disable CS1591
        Ca,
        #pragma warning restore CS1591
    }
}
