// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember1"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember2"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InitiateCallRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember1? InitiateCallRequestMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember1 InitiateCallRequestMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember2? InitiateCallRequestMember2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember2 InitiateCallRequestMember2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember3? InitiateCallRequestMember3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember3 InitiateCallRequestMember3 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequest();
            if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InitiateCallRequestMember1 = new global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember1();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InitiateCallRequestMember2 = new global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember2();
            }
            else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InitiateCallRequestMember3 = new global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember3();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(InitiateCallRequestMember1 != null)
            {
                return InitiateCallRequestMember1.GetFieldDeserializers();
            }
            else if(InitiateCallRequestMember2 != null)
            {
                return InitiateCallRequestMember2.GetFieldDeserializers();
            }
            else if(InitiateCallRequestMember3 != null)
            {
                return InitiateCallRequestMember3.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(InitiateCallRequestMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember1>(null, InitiateCallRequestMember1);
            }
            else if(InitiateCallRequestMember2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember2>(null, InitiateCallRequestMember2);
            }
            else if(InitiateCallRequestMember3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.InitiateCallRequestMember3>(null, InitiateCallRequestMember3);
            }
        }
    }
}
#pragma warning restore CS0618
