// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ListBulkSimCardActionsFilterActionTypeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "bulk_disable_voice")]
        #pragma warning disable CS1591
        BulkDisableVoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_enable_voice")]
        #pragma warning disable CS1591
        BulkEnableVoice,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_set_public_ips")]
        #pragma warning disable CS1591
        BulkSetPublicIps,
        #pragma warning restore CS1591
    }
}
