// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MessageEchoEventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "message.echo")]
        #pragma warning disable CS1591
        MessageEcho,
        #pragma warning restore CS1591
    }
}
