// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MessagingHostedNumberOrderStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "carrier_rejected")]
        #pragma warning disable CS1591
        CarrierRejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "compliance_review_failed")]
        #pragma warning disable CS1591
        ComplianceReviewFailed,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "incomplete_documentation")]
        #pragma warning disable CS1591
        IncompleteDocumentation,
        #pragma warning restore CS1591
        [EnumMember(Value = "incorrect_billing_information")]
        #pragma warning disable CS1591
        IncorrectBillingInformation,
        #pragma warning restore CS1591
        [EnumMember(Value = "ineligible_carrier")]
        #pragma warning disable CS1591
        IneligibleCarrier,
        #pragma warning restore CS1591
        [EnumMember(Value = "loa_file_invalid")]
        #pragma warning disable CS1591
        LoaFileInvalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "loa_file_successful")]
        #pragma warning disable CS1591
        LoaFileSuccessful,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "provisioning")]
        #pragma warning disable CS1591
        Provisioning,
        #pragma warning restore CS1591
        [EnumMember(Value = "successful")]
        #pragma warning disable CS1591
        Successful,
        #pragma warning restore CS1591
    }
}
