// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The messaging channel used for the message.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MessagingInboundMessagePayloadType
    {
        [EnumMember(Value = "SMS")]
        #pragma warning disable CS1591
        Sms,
        #pragma warning restore CS1591
        [EnumMember(Value = "MMS")]
        #pragma warning disable CS1591
        Mms,
        #pragma warning restore CS1591
        [EnumMember(Value = "WHATSAPP")]
        #pragma warning disable CS1591
        Whatsapp,
        #pragma warning restore CS1591
        [EnumMember(Value = "RCS")]
        #pragma warning disable CS1591
        Rcs,
        #pragma warning restore CS1591
    }
}
