// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Reason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "hard_bounce")]
        #pragma warning disable CS1591
        HardBounce,
        #pragma warning restore CS1591
        [EnumMember(Value = "spam_complaint")]
        #pragma warning disable CS1591
        SpamComplaint,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribe")]
        #pragma warning disable CS1591
        Unsubscribe,
        #pragma warning restore CS1591
        [EnumMember(Value = "invalid")]
        #pragma warning disable CS1591
        Invalid,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual_block")]
        #pragma warning disable CS1591
        ManualBlock,
        #pragma warning restore CS1591
    }
}
