// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The settlement status of the transaction. x402 transactions are created after successful on-chain settlement, so the status is `settled`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SettledStatus
    {
        [EnumMember(Value = "settled")]
        #pragma warning disable CS1591
        Settled,
        #pragma warning restore CS1591
    }
}
