// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Webhook sent when a recording starts during a TeXML call (triggered by recordingStatusCallbackEvent).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TexmlRecordingInProgressWebhookSchema : IAdditionalDataHolder, IParsable
    {
        /// <summary>The unique identifier of the account (user_id).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique identifier of the call (call_control_id).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallSid { get; set; }
#nullable restore
#else
        public string CallSid { get; set; }
#endif
        /// <summary>Legacy call identifier, same as CallSid.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallSidLegacy { get; set; }
#nullable restore
#else
        public string CallSidLegacy { get; set; }
#endif
        /// <summary>The unique identifier of the connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionId { get; set; }
#nullable restore
#else
        public string ConnectionId { get; set; }
#endif
        /// <summary>The number of channels in the recording (1 for mono, 2 for dual-channel).</summary>
        public int? RecordingChannels { get; set; }
        /// <summary>A unique identifier for the recording, generated by Telnyx (conditional, only present if recording_id is available).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordingSid { get; set; }
#nullable restore
#else
        public string RecordingSid { get; set; }
#endif
        /// <summary>The source of the recording.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordingSource { get; set; }
#nullable restore
#else
        public string RecordingSource { get; set; }
#endif
        /// <summary>The status of the recording.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.InProgressRecordingStatus? RecordingStatus { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TexmlRecordingInProgressWebhookSchema"/> and sets the default values.
        /// </summary>
        public TexmlRecordingInProgressWebhookSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TexmlRecordingInProgressWebhookSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.TexmlRecordingInProgressWebhookSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.TexmlRecordingInProgressWebhookSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccountSid", n => { AccountSid = n.GetStringValue(); } },
                { "CallSid", n => { CallSid = n.GetStringValue(); } },
                { "CallSidLegacy", n => { CallSidLegacy = n.GetStringValue(); } },
                { "ConnectionId", n => { ConnectionId = n.GetStringValue(); } },
                { "RecordingChannels", n => { RecordingChannels = n.GetIntValue(); } },
                { "RecordingSid", n => { RecordingSid = n.GetStringValue(); } },
                { "RecordingSource", n => { RecordingSource = n.GetStringValue(); } },
                { "RecordingStatus", n => { RecordingStatus = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.InProgressRecordingStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountSid", AccountSid);
            writer.WriteStringValue("CallSid", CallSid);
            writer.WriteStringValue("CallSidLegacy", CallSidLegacy);
            writer.WriteStringValue("ConnectionId", ConnectionId);
            writer.WriteIntValue("RecordingChannels", RecordingChannels);
            writer.WriteStringValue("RecordingSid", RecordingSid);
            writer.WriteStringValue("RecordingSource", RecordingSource);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.InProgressRecordingStatus>("RecordingStatus", RecordingStatus);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
