// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Webhook sent to the action URL after an HttpRequest instruction completes (when async=&quot;false&quot;). This webhook contains standard call parameters plus any custom fields extracted from the HTTP response via Field mappings defined in the Response/Content section.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TexmlHttpRequestWebhookSchema : IAdditionalDataHolder, IParsable
    {
        /// <summary>The unique identifier of the account (user_id).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSid { get; set; }
#nullable restore
#else
        public string AccountSid { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The display name of the caller (conditional, only present if caller_id_name is set).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallerId { get; set; }
#nullable restore
#else
        public string CallerId { get; set; }
#endif
        /// <summary>The unique identifier of the call (call_control_id).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallSid { get; set; }
#nullable restore
#else
        public string CallSid { get; set; }
#endif
        /// <summary>Legacy call identifier, same as CallSid.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CallSidLegacy { get; set; }
#nullable restore
#else
        public string CallSidLegacy { get; set; }
#endif
        /// <summary>The unique identifier of the connection.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionId { get; set; }
#nullable restore
#else
        public string ConnectionId { get; set; }
#endif
        /// <summary>The phone number or SIP address of the caller.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>The phone number or SIP address that was called.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? To { get; set; }
#nullable restore
#else
        public string To { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TexmlHttpRequestWebhookSchema"/> and sets the default values.
        /// </summary>
        public TexmlHttpRequestWebhookSchema()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TexmlHttpRequestWebhookSchema"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.TexmlHttpRequestWebhookSchema CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.TexmlHttpRequestWebhookSchema();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AccountSid", n => { AccountSid = n.GetStringValue(); } },
                { "CallSid", n => { CallSid = n.GetStringValue(); } },
                { "CallSidLegacy", n => { CallSidLegacy = n.GetStringValue(); } },
                { "CallerId", n => { CallerId = n.GetStringValue(); } },
                { "ConnectionId", n => { ConnectionId = n.GetStringValue(); } },
                { "From", n => { From = n.GetStringValue(); } },
                { "To", n => { To = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AccountSid", AccountSid);
            writer.WriteStringValue("CallerId", CallerId);
            writer.WriteStringValue("CallSid", CallSid);
            writer.WriteStringValue("CallSidLegacy", CallSidLegacy);
            writer.WriteStringValue("ConnectionId", ConnectionId);
            writer.WriteStringValue("From", From);
            writer.WriteStringValue("To", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
