// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>Token type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TokenResponse_token_type
    {
        [EnumMember(Value = "Bearer")]
        #pragma warning disable CS1591
        Bearer,
        #pragma warning restore CS1591
    }
}
