// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>Soniox model.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TtsRtV2ModelId
    {
        [EnumMember(Value = "tts-rt-v2")]
        #pragma warning disable CS1591
        TtsRtV2,
        #pragma warning restore CS1591
    }
}
