// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.MinimaxDesignClone"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TelnyxDesignClone"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VoiceCloneRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.MinimaxDesignClone"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.MinimaxDesignClone? MinimaxDesignClone { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.MinimaxDesignClone MinimaxDesignClone { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TelnyxDesignClone"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.TelnyxDesignClone? TelnyxDesignClone { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.TelnyxDesignClone TelnyxDesignClone { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.VoiceCloneRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.VoiceCloneRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("provider")?.GetStringValue();
            var result = new global::Soenneker.Telnyx.OpenApiClient.Models.VoiceCloneRequest();
            if("minimax".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MinimaxDesignClone = new global::Soenneker.Telnyx.OpenApiClient.Models.MinimaxDesignClone();
            }
            else if("telnyx".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TelnyxDesignClone = new global::Soenneker.Telnyx.OpenApiClient.Models.TelnyxDesignClone();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(MinimaxDesignClone != null)
            {
                return MinimaxDesignClone.GetFieldDeserializers();
            }
            else if(TelnyxDesignClone != null)
            {
                return TelnyxDesignClone.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(MinimaxDesignClone != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.MinimaxDesignClone>(null, MinimaxDesignClone);
            }
            else if(TelnyxDesignClone != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.TelnyxDesignClone>(null, TelnyxDesignClone);
            }
        }
    }
}
#pragma warning restore CS0618
