// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateBodyComponent"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateButtonsComponent"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateCarouselComponent"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateFooterComponent"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateHeaderComponent"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WhatsappCreateTemplateRequestComponentsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateBodyComponent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateBodyComponent? WhatsappTemplateBodyComponent { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateBodyComponent WhatsappTemplateBodyComponent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateButtonsComponent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateButtonsComponent? WhatsappTemplateButtonsComponent { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateButtonsComponent WhatsappTemplateButtonsComponent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateCarouselComponent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateCarouselComponent? WhatsappTemplateCarouselComponent { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateCarouselComponent WhatsappTemplateCarouselComponent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateFooterComponent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateFooterComponent? WhatsappTemplateFooterComponent { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateFooterComponent WhatsappTemplateFooterComponent { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateHeaderComponent"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateHeaderComponent? WhatsappTemplateHeaderComponent { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateHeaderComponent WhatsappTemplateHeaderComponent { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappCreateTemplateRequestComponentsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappCreateTemplateRequestComponentsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappCreateTemplateRequestComponentsItem();
            if("WhatsappTemplateBodyComponent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WhatsappTemplateBodyComponent = new global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateBodyComponent();
            }
            else if("WhatsappTemplateButtonsComponent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WhatsappTemplateButtonsComponent = new global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateButtonsComponent();
            }
            else if("WhatsappTemplateCarouselComponent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WhatsappTemplateCarouselComponent = new global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateCarouselComponent();
            }
            else if("WhatsappTemplateFooterComponent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WhatsappTemplateFooterComponent = new global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateFooterComponent();
            }
            else if("WhatsappTemplateHeaderComponent".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.WhatsappTemplateHeaderComponent = new global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateHeaderComponent();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(WhatsappTemplateBodyComponent != null)
            {
                return WhatsappTemplateBodyComponent.GetFieldDeserializers();
            }
            else if(WhatsappTemplateButtonsComponent != null)
            {
                return WhatsappTemplateButtonsComponent.GetFieldDeserializers();
            }
            else if(WhatsappTemplateCarouselComponent != null)
            {
                return WhatsappTemplateCarouselComponent.GetFieldDeserializers();
            }
            else if(WhatsappTemplateFooterComponent != null)
            {
                return WhatsappTemplateFooterComponent.GetFieldDeserializers();
            }
            else if(WhatsappTemplateHeaderComponent != null)
            {
                return WhatsappTemplateHeaderComponent.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(WhatsappTemplateBodyComponent != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateBodyComponent>(null, WhatsappTemplateBodyComponent);
            }
            else if(WhatsappTemplateButtonsComponent != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateButtonsComponent>(null, WhatsappTemplateButtonsComponent);
            }
            else if(WhatsappTemplateCarouselComponent != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateCarouselComponent>(null, WhatsappTemplateCarouselComponent);
            }
            else if(WhatsappTemplateFooterComponent != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateFooterComponent>(null, WhatsappTemplateFooterComponent);
            }
            else if(WhatsappTemplateHeaderComponent != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappTemplateHeaderComponent>(null, WhatsappTemplateHeaderComponent);
            }
        }
    }
}
#pragma warning restore CS0618
