// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WhatsappPhoneResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The calling_enabled property</summary>
        public bool? CallingEnabled { get; set; }
        /// <summary>Current lifecycle state for a coexistence number. This is null for a standard Cloud API number.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseCoexistenceState? CoexistenceState { get; set; }
        /// <summary>The created_at property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The display_name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>Indicates whether the number is connected to both the WhatsApp Business app and Cloud API through WhatsApp Coexistence.</summary>
        public bool? IsOnBizApp { get; set; }
        /// <summary>Phone number in E164 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>Whatsapp phone number ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumberId { get; set; }
#nullable restore
#else
        public string PhoneNumberId { get; set; }
#endif
        /// <summary>Whatsapp quality rating</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QualityRating { get; set; }
#nullable restore
#else
        public string QualityRating { get; set; }
#endif
        /// <summary>The record_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordType { get; set; }
#nullable restore
#else
        public string RecordType { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Deadline for initiating the current coexistence synchronization cycle. This is null when no deadline applies.</summary>
        public DateTimeOffset? SyncDeadline { get; set; }
        /// <summary>Synchronization progress. This object is returned only while a coexistence number is synchronizing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseSyncProgress? SyncProgress { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseSyncProgress SyncProgress { get; set; }
#endif
        /// <summary>User ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>WABA ID of Whatsapp business account</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WabaId { get; set; }
#nullable restore
#else
        public string WabaId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponse"/> and sets the default values.
        /// </summary>
        public WhatsappPhoneResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calling_enabled", n => { CallingEnabled = n.GetBoolValue(); } },
                { "coexistence_state", n => { CoexistenceState = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseCoexistenceState>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "is_on_biz_app", n => { IsOnBizApp = n.GetBoolValue(); } },
                { "phone_number", n => { PhoneNumber = n.GetStringValue(); } },
                { "phone_number_id", n => { PhoneNumberId = n.GetStringValue(); } },
                { "quality_rating", n => { QualityRating = n.GetStringValue(); } },
                { "record_type", n => { RecordType = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "sync_deadline", n => { SyncDeadline = n.GetDateTimeOffsetValue(); } },
                { "sync_progress", n => { SyncProgress = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseSyncProgress>(global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseSyncProgress.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetStringValue(); } },
                { "waba_id", n => { WabaId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("calling_enabled", CallingEnabled);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseCoexistenceState>("coexistence_state", CoexistenceState);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("is_on_biz_app", IsOnBizApp);
            writer.WriteStringValue("phone_number", PhoneNumber);
            writer.WriteStringValue("phone_number_id", PhoneNumberId);
            writer.WriteStringValue("quality_rating", QualityRating);
            writer.WriteStringValue("record_type", RecordType);
            writer.WriteStringValue("status", Status);
            writer.WriteDateTimeOffsetValue("sync_deadline", SyncDeadline);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.WhatsappPhoneResponseSyncProgress>("sync_progress", SyncProgress);
            writer.WriteStringValue("user_id", UserId);
            writer.WriteStringValue("waba_id", WabaId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
