// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Telnyx.OpenApiClient.Rcs.Agents;
using Soenneker.Telnyx.OpenApiClient.Rcs.Brands;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Rcs
{
    /// <summary>
    /// Builds and executes requests for operations under \rcs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RcsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The agents property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Rcs.Agents.AgentsRequestBuilder Agents
        {
            get => new global::Soenneker.Telnyx.OpenApiClient.Rcs.Agents.AgentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The brands property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Rcs.Brands.BrandsRequestBuilder Brands
        {
            get => new global::Soenneker.Telnyx.OpenApiClient.Rcs.Brands.BrandsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Rcs.RcsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RcsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rcs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Rcs.RcsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RcsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/rcs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
