// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Business_accounts;
using Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Message_templates;
using Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Phone_numbers;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Telnyx.OpenApiClient.V2.Whatsapp
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\whatsapp
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WhatsappRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The business_accounts property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Business_accounts.Business_accountsRequestBuilder Business_accounts
        {
            get => new global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Business_accounts.Business_accountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The message_templates property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Message_templates.Message_templatesRequestBuilder Message_templates
        {
            get => new global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Message_templates.Message_templatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The phone_numbers property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Phone_numbers.Phone_numbersRequestBuilder Phone_numbers
        {
            get => new global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.Phone_numbers.Phone_numbersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.WhatsappRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WhatsappRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/whatsapp", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.V2.Whatsapp.WhatsappRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WhatsappRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/whatsapp", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
