// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.Models
{
    /// <summary>When set to `trim-silence`, silence will be removed from the beginning and end of the recording.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BridgeRequest_record_trim
    {
        [EnumMember(Value = "trim-silence")]
        #pragma warning disable CS1591
        TrimSilence,
        #pragma warning restore CS1591
    }
}
