// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>Identifies the type of report</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreatePortingReport_report_type
    {
        [EnumMember(Value = "export_porting_orders_csv")]
        #pragma warning disable CS1591
        Export_porting_orders_csv,
        #pragma warning restore CS1591
    }
}
