// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectListResponse_Wrapper"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjecToObjecttResponse"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectToStringResponse"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumPaginatedResponse"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumStringListResponse_Wrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetEnumEndpoint_200 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectListResponse_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectListResponse_Wrapper? EnumObjectListResponseWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectListResponse_Wrapper EnumObjectListResponseWrapper { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjecToObjecttResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjecToObjecttResponse? EnumObjecToObjecttResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjecToObjecttResponse EnumObjecToObjecttResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectToStringResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectToStringResponse? EnumObjectToStringResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectToStringResponse EnumObjectToStringResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumPaginatedResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumPaginatedResponse? EnumPaginatedResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumPaginatedResponse EnumPaginatedResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.EnumStringListResponse_Wrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumStringListResponse_Wrapper? EnumStringListResponseWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.EnumStringListResponse_Wrapper EnumStringListResponseWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.GetEnumEndpoint_200"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.GetEnumEndpoint_200 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Telnyx.OpenApiClient.Models.GetEnumEndpoint_200();
            if("EnumObjecToObjecttResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnumObjecToObjecttResponse = new global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjecToObjecttResponse();
            }
            else if("EnumObjectListResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnumObjectListResponseWrapper = new global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectListResponse_Wrapper();
            }
            else if("EnumObjectToStringResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnumObjectToStringResponse = new global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectToStringResponse();
            }
            else if("EnumPaginatedResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnumPaginatedResponse = new global::Soenneker.Telnyx.OpenApiClient.Models.EnumPaginatedResponse();
            }
            else if("EnumStringListResponse".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EnumStringListResponseWrapper = new global::Soenneker.Telnyx.OpenApiClient.Models.EnumStringListResponse_Wrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(EnumObjectListResponseWrapper != null)
            {
                return EnumObjectListResponseWrapper.GetFieldDeserializers();
            }
            else if(EnumObjecToObjecttResponse != null)
            {
                return EnumObjecToObjecttResponse.GetFieldDeserializers();
            }
            else if(EnumObjectToStringResponse != null)
            {
                return EnumObjectToStringResponse.GetFieldDeserializers();
            }
            else if(EnumPaginatedResponse != null)
            {
                return EnumPaginatedResponse.GetFieldDeserializers();
            }
            else if(EnumStringListResponseWrapper != null)
            {
                return EnumStringListResponseWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(EnumObjectListResponseWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectListResponse_Wrapper>(null, EnumObjectListResponseWrapper);
            }
            else if(EnumObjecToObjecttResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjecToObjecttResponse>(null, EnumObjecToObjecttResponse);
            }
            else if(EnumObjectToStringResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnumObjectToStringResponse>(null, EnumObjectToStringResponse);
            }
            else if(EnumPaginatedResponse != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnumPaginatedResponse>(null, EnumPaginatedResponse);
            }
            else if(EnumStringListResponseWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.EnumStringListResponse_Wrapper>(null, EnumStringListResponseWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
