// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum MdrDetailReportResponse_directions
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "INBOUND")]
        #pragma warning disable CS1591
        INBOUND,
        #pragma warning restore CS1591
        [EnumMember(Value = "OUTBOUND")]
        #pragma warning disable CS1591
        OUTBOUND,
        #pragma warning restore CS1591
    }
}
