// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PhoneNumberDeletedDetailed : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Identifies the billing group associated with the phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingGroupId { get; set; }
#nullable restore
#else
        public string BillingGroupId { get; set; }
#endif
        /// <summary>Indicates whether caller ID is enabled for this number.</summary>
        public bool? CallerIdNameEnabled { get; private set; }
        /// <summary>Indicates if call forwarding will be enabled for this number if forwards_to and forwarding_type are filled in. Defaults to true for backwards compatibility with APIV1 use of numbers endpoints.</summary>
        public bool? CallForwardingEnabled { get; private set; }
        /// <summary>Indicates whether call recording is enabled for this number.</summary>
        public bool? CallRecordingEnabled { get; private set; }
        /// <summary>Indicates whether a CNAM listing is enabled for this number.</summary>
        public bool? CnamListingEnabled { get; private set; }
        /// <summary>Identifies the connection associated with the phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionId { get; set; }
#nullable restore
#else
        public string ConnectionId { get; set; }
#endif
        /// <summary>The user-assigned name of the connection to be associated with this phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionName { get; private set; }
#nullable restore
#else
        public string ConnectionName { get; private set; }
#endif
        /// <summary>ISO 8601 formatted date indicating when the time it took to activate after the purchase.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; private set; }
#nullable restore
#else
        public string CreatedAt { get; private set; }
#endif
        /// <summary>A customer reference string for customer look ups.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerReference { get; set; }
#nullable restore
#else
        public string CustomerReference { get; set; }
#endif
        /// <summary>Identifies the emergency address associated with the phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmergencyAddressId { get; private set; }
#nullable restore
#else
        public string EmergencyAddressId { get; private set; }
#endif
        /// <summary>Indicates whether emergency services are enabled for this number.</summary>
        public bool? EmergencyEnabled { get; private set; }
        /// <summary>If someone attempts to port your phone number away from Telnyx and your phone number has an external PIN set, Telnyx will attempt to verify that you provided the correct external PIN to the winning carrier. Note that not all carriers cooperate with this security mechanism.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalPin { get; set; }
#nullable restore
#else
        public string ExternalPin { get; set; }
#endif
        /// <summary>Uniquely identifies the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Identifies the messaging profile associated with the phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessagingProfileId { get; set; }
#nullable restore
#else
        public string MessagingProfileId { get; set; }
#endif
        /// <summary>The name of the messaging profile associated with the phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessagingProfileName { get; set; }
#nullable restore
#else
        public string MessagingProfileName { get; set; }
#endif
        /// <summary>The +E.164-formatted phone number associated with this record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; private set; }
#nullable restore
#else
        public string PhoneNumber { get; private set; }
#endif
        /// <summary>The phone number&apos;s type.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed_phone_number_type? PhoneNumberType { get; private set; }
        /// <summary>ISO 8601 formatted date indicating the time the request was made to purchase the number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PurchasedAt { get; private set; }
#nullable restore
#else
        public string PurchasedAt { get; private set; }
#endif
        /// <summary>Identifies the type of the resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecordType { get; private set; }
#nullable restore
#else
        public string RecordType { get; private set; }
#endif
        /// <summary>The phone number&apos;s current status.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed_status? Status { get; private set; }
        /// <summary>Indicates whether T38 Fax Gateway for inbound calls to this number.</summary>
        public bool? T38FaxGatewayEnabled { get; private set; }
        /// <summary>A list of user-assigned tags to help manage the phone number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>ISO 8601 formatted date indicating when the resource was updated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; private set; }
#nullable restore
#else
        public string UpdatedAt { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed"/> and sets the default values.
        /// </summary>
        public PhoneNumberDeletedDetailed()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing_group_id", n => { BillingGroupId = n.GetStringValue(); } },
                { "call_forwarding_enabled", n => { CallForwardingEnabled = n.GetBoolValue(); } },
                { "call_recording_enabled", n => { CallRecordingEnabled = n.GetBoolValue(); } },
                { "caller_id_name_enabled", n => { CallerIdNameEnabled = n.GetBoolValue(); } },
                { "cnam_listing_enabled", n => { CnamListingEnabled = n.GetBoolValue(); } },
                { "connection_id", n => { ConnectionId = n.GetStringValue(); } },
                { "connection_name", n => { ConnectionName = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "customer_reference", n => { CustomerReference = n.GetStringValue(); } },
                { "emergency_address_id", n => { EmergencyAddressId = n.GetStringValue(); } },
                { "emergency_enabled", n => { EmergencyEnabled = n.GetBoolValue(); } },
                { "external_pin", n => { ExternalPin = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "messaging_profile_id", n => { MessagingProfileId = n.GetStringValue(); } },
                { "messaging_profile_name", n => { MessagingProfileName = n.GetStringValue(); } },
                { "phone_number", n => { PhoneNumber = n.GetStringValue(); } },
                { "phone_number_type", n => { PhoneNumberType = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed_phone_number_type>(); } },
                { "purchased_at", n => { PurchasedAt = n.GetStringValue(); } },
                { "record_type", n => { RecordType = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.PhoneNumberDeletedDetailed_status>(); } },
                { "t38_fax_gateway_enabled", n => { T38FaxGatewayEnabled = n.GetBoolValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("billing_group_id", BillingGroupId);
            writer.WriteStringValue("connection_id", ConnectionId);
            writer.WriteStringValue("customer_reference", CustomerReference);
            writer.WriteStringValue("external_pin", ExternalPin);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("messaging_profile_id", MessagingProfileId);
            writer.WriteStringValue("messaging_profile_name", MessagingProfileName);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
