// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>Type of value expected on field_value field</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PortingOrderRequirementDetail_field_type
    {
        [EnumMember(Value = "document")]
        #pragma warning disable CS1591
        Document,
        #pragma warning restore CS1591
        [EnumMember(Value = "textual")]
        #pragma warning disable CS1591
        Textual,
        #pragma warning restore CS1591
    }
}
