// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.AssignProfileToCampaignResponse"/>, <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.SettingsDataErrorMessage"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostAssignMessagingProfileToCampaign_202 : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.AssignProfileToCampaignResponse"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.AssignProfileToCampaignResponse? AssignProfileToCampaignResponse { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.AssignProfileToCampaignResponse AssignProfileToCampaignResponse { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.SettingsDataErrorMessage"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.SettingsDataErrorMessage? SettingsDataErrorMessage { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.SettingsDataErrorMessage SettingsDataErrorMessage { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.PostAssignMessagingProfileToCampaign_202"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.PostAssignMessagingProfileToCampaign_202 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Telnyx.OpenApiClient.Models.PostAssignMessagingProfileToCampaign_202();
            result.AssignProfileToCampaignResponse = new global::Soenneker.Telnyx.OpenApiClient.Models.AssignProfileToCampaignResponse();
            result.SettingsDataErrorMessage = new global::Soenneker.Telnyx.OpenApiClient.Models.SettingsDataErrorMessage();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AssignProfileToCampaignResponse != null || SettingsDataErrorMessage != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AssignProfileToCampaignResponse, SettingsDataErrorMessage);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.AssignProfileToCampaignResponse>(null, AssignProfileToCampaignResponse, SettingsDataErrorMessage);
        }
    }
}
#pragma warning restore CS0618
