// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Queue_record_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "queue")]
        #pragma warning disable CS1591
        Queue,
        #pragma warning restore CS1591
    }
}
