// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The type of SIM card</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SIMCard_type
    {
        [EnumMember(Value = "physical")]
        #pragma warning disable CS1591
        Physical,
        #pragma warning restore CS1591
        [EnumMember(Value = "esim")]
        #pragma warning disable CS1591
        Esim,
        #pragma warning restore CS1591
    }
}
