// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>
    /// Action to take when voicemail is detected.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TelephonySettings_voicemail_detection_on_voicemail_detected : IAdditionalDataHolder, IParsable
    {
        /// <summary>The action to take when voicemail is detected.</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_action? Action { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Configuration for the voicemail message to leave. Only applicable when action is &apos;leave_message_and_stop_assistant&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_voicemail_message? VoicemailMessage { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_voicemail_message VoicemailMessage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected"/> and sets the default values.
        /// </summary>
        public TelephonySettings_voicemail_detection_on_voicemail_detected()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_action>(); } },
                { "voicemail_message", n => { VoicemailMessage = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_voicemail_message>(global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_voicemail_message.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_action>("action", Action);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.TelephonySettings_voicemail_detection_on_voicemail_detected_voicemail_message>("voicemail_message", VoicemailMessage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
