// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.Models
{
    /// <summary>Campaign status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TelnyxCampaignWithAssignedCount_CSP_campaignStatus
    {
        [EnumMember(Value = "TCR_PENDING")]
        #pragma warning disable CS1591
        TCR_PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "TCR_SUSPENDED")]
        #pragma warning disable CS1591
        TCR_SUSPENDED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TCR_EXPIRED")]
        #pragma warning disable CS1591
        TCR_EXPIRED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TCR_ACCEPTED")]
        #pragma warning disable CS1591
        TCR_ACCEPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TCR_FAILED")]
        #pragma warning disable CS1591
        TCR_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TELNYX_ACCEPTED")]
        #pragma warning disable CS1591
        TELNYX_ACCEPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "TELNYX_FAILED")]
        #pragma warning disable CS1591
        TELNYX_FAILED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MNO_PENDING")]
        #pragma warning disable CS1591
        MNO_PENDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "MNO_ACCEPTED")]
        #pragma warning disable CS1591
        MNO_ACCEPTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MNO_REJECTED")]
        #pragma warning disable CS1591
        MNO_REJECTED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MNO_PROVISIONED")]
        #pragma warning disable CS1591
        MNO_PROVISIONED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MNO_PROVISIONING_FAILED")]
        #pragma warning disable CS1591
        MNO_PROVISIONING_FAILED,
        #pragma warning restore CS1591
    }
}
