// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateMissionRunRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The error property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_metadata Metadata { get; set; }
#endif
        /// <summary>The result_payload property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_result_payload? ResultPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_result_payload ResultPayload { get; set; }
#endif
        /// <summary>The result_summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultSummary { get; set; }
#nullable restore
#else
        public string ResultSummary { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Telnyx.OpenApiClient.Models.RunStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest"/> and sets the default values.
        /// </summary>
        public UpdateMissionRunRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "error", n => { Error = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_metadata>(global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_metadata.CreateFromDiscriminatorValue); } },
                { "result_payload", n => { ResultPayload = n.GetObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_result_payload>(global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_result_payload.CreateFromDiscriminatorValue); } },
                { "result_summary", n => { ResultSummary = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.RunStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("error", Error);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_metadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Telnyx.OpenApiClient.Models.UpdateMissionRunRequest_result_payload>("result_payload", ResultPayload);
            writer.WriteStringValue("result_summary", ResultSummary);
            writer.WriteEnumValue<global::Soenneker.Telnyx.OpenApiClient.Models.RunStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
