// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Models
{
    /// <summary>The predefined media to use. `silence` disables background audio.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VoiceSettings_background_audioMember1_value
    {
        [EnumMember(Value = "silence")]
        #pragma warning disable CS1591
        Silence,
        #pragma warning restore CS1591
        [EnumMember(Value = "office")]
        #pragma warning disable CS1591
        Office,
        #pragma warning restore CS1591
    }
}
