// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Telnyx.CampaignBuilder.Brand.Item.Usecase.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Telnyx.CampaignBuilder.Brand.Item.Usecase
{
    /// <summary>
    /// Builds and executes requests for operations under \campaignBuilder\brand\{brandId}\usecase
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsecaseRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Telnyx.campaignBuilder.brand.item.usecase.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Telnyx.CampaignBuilder.Brand.Item.Usecase.Item.WithUsecaseItemRequestBuilder"/></returns>
        public global::Soenneker.Telnyx.CampaignBuilder.Brand.Item.Usecase.Item.WithUsecaseItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("usecase", position);
                return new global::Soenneker.Telnyx.CampaignBuilder.Brand.Item.Usecase.Item.WithUsecaseItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.CampaignBuilder.Brand.Item.Usecase.UsecaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsecaseRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaignBuilder/brand/{brandId}/usecase", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Telnyx.CampaignBuilder.Brand.Item.Usecase.UsecaseRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsecaseRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/campaignBuilder/brand/{brandId}/usecase", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
