// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Portouts.Events.Item.Republish
{
    /// <summary>
    /// Default response schema
    /// </summary>
    [Obsolete("This class is obsolete. Use RepublishPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RepublishResponse : global::Soenneker.Telnyx.OpenApiClient.Portouts.Events.Item.Republish.RepublishPostResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Telnyx.OpenApiClient.Portouts.Events.Item.Republish.RepublishResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Telnyx.OpenApiClient.Portouts.Events.Item.Republish.RepublishResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Telnyx.OpenApiClient.Portouts.Events.Item.Republish.RepublishResponse();
        }
    }
}
#pragma warning restore CS0618
