// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Telnyx.OpenApiClient.Requirements
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFilterPhone_number_typeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "local")]
        #pragma warning disable CS1591
        Local,
        #pragma warning restore CS1591
        [EnumMember(Value = "national")]
        #pragma warning disable CS1591
        National,
        #pragma warning restore CS1591
        [EnumMember(Value = "toll_free")]
        #pragma warning disable CS1591
        Toll_free,
        #pragma warning restore CS1591
    }
}
